In [1]:
import numpy as np

# initialization

## array

In [2]:

print(np.arange(5))
print(np.arange(0, 11, 2))  # exclude 11, gap = 2

print(np.linspace(0, 10, 6))  # include 10, number=6
print(np.linspace(0, 2 * np.pi, 10))
# np.logspace(0,2,10)

print(np.zeros(3))
print(np.ones(3))

[0 1 2 3 4]
[ 0  2  4  6  8 10]
[ 0.  2.  4.  6.  8. 10.]
[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]
[0. 0. 0.]
[1. 1. 1.]


## matrix

In [3]:
print(np.zeros((3, 3)))
print(np.ones((3, 3)))
print(np.eye(3))

t0 = np.array([[1, 2], [3, 4]])
print(np.tile(t0, (2, 2)))

a = np.array([1, 4, 2, 6, 7, 8, 9, 3, 4, 6, 4, 5, 7, 3, 6, 2.3])
print(a.shape)

# not a fixed array
A = a.reshape(4, 4)  # the row order is keeped
# use resize will change the a
print("A=", A)  # remember the A here

x1 = np.random.randn(3, 3)
print(x1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]]
(16,)
A= [[1.  4.  2.  6. ]
 [7.  8.  9.  3. ]
 [4.  6.  4.  5. ]
 [7.  3.  6.  2.3]]
[[ 0.94984     0.54460447  1.35147948]
 [ 2.00190199  2.14258954 -1.13516428]
 [-0.55999489 -0.6877902  -0.79910526]]


# 1 - np functions on np.array

In [4]:
xn = np.random.randn(100000)  # randn is normalvariate
# %time print(sum(xn))
# %time print(np.sum(xn))  # np function is incrediablely faster

# entry-wise
print(np.exp(xn))  # this is crazy for for loop
print(np.sqrt(np.abs(xn)))
print(np.floor(xn))


[1.88352674 0.59186428 1.32579648 ... 1.12834144 1.11537993 1.09663029]
[0.79570468 0.72420848 0.53104934 ... 0.34748928 0.33044681 0.30371385]
[ 0. -1.  0. ...  0.  0.  0.]


In [5]:
# more np functions:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)

print(np.sum(A,  axis=0))  
# axis = 0 means columnwise (like sum up the 0th dimension)

print(np.sum(A,  axis=1))
print(np.prod(A, axis=0))

[[1 2 3]
 [4 5 6]]
[5 7 9]
[ 6 15]
[ 4 10 18]


In [6]:
print(np.cumsum(A, axis=1))
print(np.diff(A,   axis=1))  # a[n] = x[n+1] -x[n]

[[ 1  3  6]
 [ 4  9 15]]
[[1 1]
 [1 1]]


In [7]:
print(np.var(A, axis=1))
print(np.std(A, axis=1))

[0.66666667 0.66666667]
[0.81649658 0.81649658]


In [8]:
print(np.max(A,    axis=1))
print(np.argmax(A, axis=1))

[3 6]
[2 2]


In [9]:
A = np.array([[2, 1],[6, 3]])
print(np.sort(A, axis=1))
print(A)
print(np.argsort(A.ravel()))  # order

[[1 2]
 [3 6]]
[[2 1]
 [6 3]]
[1 0 3 2]


In [10]:
# list of boolean
logic = [True, True, False, True]

print(np.logical_not(logic))
print(np.where(logic))
  
# another ways to use np.where
print(np.where(logic, range(4), range(0, 40, 10)))
# true for range(4)
# false for range(0, 40, 10)

print(np.nonzero([0, 2, 0, 1]))
# it is better to not use it on boolean

[False False  True False]
(array([0, 1, 3]),)
[ 0  1 20  3]
(array([1, 3]),)


# 2 - matrix

## 2.1 matrix operations

In [11]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
# 1) index
print(A[1, 2])
print(A[(1, 2)])
print(A[:, 2])

print(A[0])  # the first row
print(A[[0, 2]])  # 2 rows
print(A[[0, 2], [0, 2]])

6
6
[3 6 9]
[1 2 3]
[[1 2 3]
 [7 8 9]]
[1 9]


In [13]:
# sampling
x = np.arange(100)

x_sample = x[::10]
print(x_sample)

x_reverse = x[::-1]
print(x_reverse)

[ 0 10 20 30 40 50 60 70 80 90]
[99 98 97 96 95 94 93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76
 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52
 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28
 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4
  3  2  1  0]


In [14]:
# 2) reshape and ravel

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(A.reshape(2, -1, order='F'))  # -1 means adaptive
# order: 
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html

print(A.ravel())  # return to vector

[[ 1  7  2  8  3  9]
 [ 4 10  5 11  6 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [15]:
# 3) np.dot (faster than for loop multiplicaiton)
x = np.array([1, 2, 3])
x = x.reshape(3, 1)
b = np.dot(A, x)  # weapon of vectorization
print(b)


[[14]
 [32]
 [50]
 [68]]


In [16]:
# important: when one of the input lack dimension, it will be adaptive
a = np.random.randn(5)
print(a.shape)
print(a.T)
print(np.dot(a.T, a))

(5,)
[-1.0405038  -0.50470267  0.04238699 -0.90393582 -1.13863205]
3.4527525305249362


In [17]:
# 4) stack and split

a = np.floor(10 * np.random.random((2, 12)))
b = np.floor(10 * np.random.random((2, 12)))
print('a\n', a)
print('b\n', b)

# stack
print(np.hstack((a, b)))
print(np.c_[a, b])  # increase columns

print(np.vstack((a, b)))
print(np.r_[a, b])  # increase rows

# split
print(np.hsplit(a, 3))  # evenly into 3 part
print(np.hsplit(a, (3, 4)))  # 表示从某位置切割  (3, 4)  切两下 最左边记为0 第一块有3列

print(np.vsplit(b, 2))




a
 [[0. 4. 0. 3. 4. 3. 2. 8. 6. 5. 6. 3.]
 [0. 5. 4. 6. 5. 3. 8. 6. 4. 4. 1. 5.]]
b
 [[0. 5. 3. 7. 7. 7. 9. 2. 6. 5. 0. 8.]
 [9. 8. 3. 3. 3. 6. 9. 3. 5. 7. 5. 6.]]
[[0. 4. 0. 3. 4. 3. 2. 8. 6. 5. 6. 3. 0. 5. 3. 7. 7. 7. 9. 2. 6. 5. 0. 8.]
 [0. 5. 4. 6. 5. 3. 8. 6. 4. 4. 1. 5. 9. 8. 3. 3. 3. 6. 9. 3. 5. 7. 5. 6.]]
[[0. 4. 0. 3. 4. 3. 2. 8. 6. 5. 6. 3. 0. 5. 3. 7. 7. 7. 9. 2. 6. 5. 0. 8.]
 [0. 5. 4. 6. 5. 3. 8. 6. 4. 4. 1. 5. 9. 8. 3. 3. 3. 6. 9. 3. 5. 7. 5. 6.]]
[[0. 4. 0. 3. 4. 3. 2. 8. 6. 5. 6. 3.]
 [0. 5. 4. 6. 5. 3. 8. 6. 4. 4. 1. 5.]
 [0. 5. 3. 7. 7. 7. 9. 2. 6. 5. 0. 8.]
 [9. 8. 3. 3. 3. 6. 9. 3. 5. 7. 5. 6.]]
[[0. 4. 0. 3. 4. 3. 2. 8. 6. 5. 6. 3.]
 [0. 5. 4. 6. 5. 3. 8. 6. 4. 4. 1. 5.]
 [0. 5. 3. 7. 7. 7. 9. 2. 6. 5. 0. 8.]
 [9. 8. 3. 3. 3. 6. 9. 3. 5. 7. 5. 6.]]
[array([[0., 4., 0., 3.],
       [0., 5., 4., 6.]]), array([[4., 3., 2., 8.],
       [5., 3., 8., 6.]]), array([[6., 5., 6., 3.],
       [4., 4., 1., 5.]])]
[array([[0., 4., 0.],
       [0., 5., 4.]]), array([[3.],
     

## 2.2 matrix broadcasting

In [18]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print('A\n', A)
print(A + 2)
print(A + np.array([[0, 1, -100]]))
print(A + np.array([[0, 1, -100]]).T)

# practice
np.sum(A, axis=0)
print(A / np.sum(A, axis=0))


A
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[  1   3 -97]
 [  4   6 -94]
 [  7   9 -91]]
[[  1   2   3]
 [  5   6   7]
 [-93 -92 -91]]
[[0.08333333 0.13333333 0.16666667]
 [0.33333333 0.33333333 0.33333333]
 [0.58333333 0.53333333 0.5       ]]


# program operation

In [19]:
a = np.array([[1, 4, 2, 6, 7, 8, 9, 3, 4, 6, 4, 5, 7, 3, 6, 2.3]])
a2 = a
a_copy = a.copy()
a_view = a.view()

a[0, 0] = 10
print(a)
print(a2)
print(a_copy)
print(a_view)

a = np.array([[1, 4, 2, 6, 7, 8, 9, 3, 4, 6, 4, 5, 7, 3, 6, 2.3]])
a2 = a
a_copy = a.copy()
a_view = a.view()

a.shape = (4, 4)
a[0, 0] = 10
print(a)
print(a2)
print(a_copy)
print(a_view)

[[10.   4.   2.   6.   7.   8.   9.   3.   4.   6.   4.   5.   7.   3.
   6.   2.3]]
[[10.   4.   2.   6.   7.   8.   9.   3.   4.   6.   4.   5.   7.   3.
   6.   2.3]]
[[1.  4.  2.  6.  7.  8.  9.  3.  4.  6.  4.  5.  7.  3.  6.  2.3]]
[[10.   4.   2.   6.   7.   8.   9.   3.   4.   6.   4.   5.   7.   3.
   6.   2.3]]
[[10.   4.   2.   6. ]
 [ 7.   8.   9.   3. ]
 [ 4.   6.   4.   5. ]
 [ 7.   3.   6.   2.3]]
[[10.   4.   2.   6. ]
 [ 7.   8.   9.   3. ]
 [ 4.   6.   4.   5. ]
 [ 7.   3.   6.   2.3]]
[[1.  4.  2.  6.  7.  8.  9.  3.  4.  6.  4.  5.  7.  3.  6.  2.3]]
[[10.   4.   2.   6.   7.   8.   9.   3.   4.   6.   4.   5.   7.   3.
   6.   2.3]]


# bonus operation

In [20]:
# np.c_ for 1 dim array
A = np.arange(6)
print(np.c_[A, A])

# np.meshgrid
xx, yy = np.meshgrid(A, A)
all_node = zip(xx.ravel(), yy.ravel())
print(list(all_node))

# np.all
np.all([True, False])
np.any([True, False])

# np.apply_along_axis
np.apply_along_axis(lambda x: np.sum(x), 0, A.reshape(2, 3))

# cov
y = x
X = np.concatenate([x, y])
np.cov(x, y)
np.cov(X.T)  # each column of X is an attribute

np.corrcoef(x, y)

[[0 0]
 [1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]]
[(0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (5, 0), (0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (0, 2), (1, 2), (2, 2), (3, 2), (4, 2), (5, 2), (0, 3), (1, 3), (2, 3), (3, 3), (4, 3), (5, 3), (0, 4), (1, 4), (2, 4), (3, 4), (4, 4), (5, 4), (0, 5), (1, 5), (2, 5), (3, 5), (4, 5), (5, 5)]


/home/congyu/.virtualenvs/congyuml/lib/python3.6/site-packages/ipykernel_launcher.py:20: RuntimeWarning: Degrees of freedom <= 0 for slice
/home/congyu/.virtualenvs/congyuml/lib/python3.6/site-packages/numpy/lib/function_base.py:2455: RuntimeWarning: divide by zero encountered in true_divide
  c *= np.true_divide(1, fact)
/home/congyu/.virtualenvs/congyuml/lib/python3.6/site-packages/numpy/lib/function_base.py:2455: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
/home/congyu/.virtualenvs/congyuml/lib/python3.6/site-packages/numpy/lib/function_base.py:2526: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar)


array([[nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan]])

# Handbook of numpy

In [21]:
a = np.arange(12)
print(a)

print(a.ndim)
print(a.shape)
print(a.size)

# numpy initialization
A = a.reshape(3, 4)
np.ones_like(a)
np.zeros_like(a)

B1 = np.random.rand(4, 3)
B2 = np.random.randn(4, 3)

# say that we want a matrix aij = i+j
np.fromfunction(lambda i, j: i + j, (3, 3))

a = np.arange(9)
idx = [1, 3, 1, 4]
print(np.take(a, idx))

idx = [[1, 2, -1], [1, 2, -1]]
print(np.take(a, idx))

# alter value
print(a)
np.put(a, [0, -1], [10, 20])  # put 10 in position 0, put 20 to the last position
print(a)

# matrix operation
A @ B1  # np.dot

np.repeat([1, 2, 3], 5).reshape(3, 5)

# delete newaxis
np.squeeze(A)

np.ptp(range(10))  # value_range (max-min)
np.ptp(np.ones(10))
np.ptp([[1, 2, 3], [2, 3, 4]], axis=0)
np.ptp([[1, 2, 3], [2, 3, 4]], axis=1)

# return the indices where elements should be inserted to maintain order.
np.searchsorted(range(10), 5)  # find the position of 5
np.searchsorted(range(10), 5, side='left')  # left is empty boundary



[ 0  1  2  3  4  5  6  7  8  9 10 11]
1
(12,)
12
[1 3 1 4]
[[1 2 8]
 [1 2 8]]
[0 1 2 3 4 5 6 7 8]
[10  1  2  3  4  5  6  7 20]


5

In [22]:
# newaxis
from numpy import newaxis

# it is None

a = np.arange(10)
print(a.shape)
b = a[newaxis, :]
print(b.shape)

b = a[:, newaxis]
print(b.shape)

a = a[:-1]
A = a.reshape(3, 3)
B = A[:, newaxis, :]
print(B)

(10,)
(1, 10)
(10, 1)
[[[0 1 2]]

 [[3 4 5]]

 [[6 7 8]]]


In [23]:
from numpy import linalg

A = np.array([[1, 2], [0, 3]])
b = np.array([5, 2])

A_ = linalg.solve(A, np.ones(len(A)))
x  = linalg.solve(A, b)

In [24]:
w, v = linalg.eig(A)
print(w)
print(v)

u, s, vh = linalg.svd(A)

[1. 3.]
[[1.         0.70710678]
 [0.         0.70710678]]
